/*
 * This Java source file was generated by the Gradle 'init' ru.nsu.cherepanov.task.
 */
package ru.nsu.cherepanov.task;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
    }
}
